# SITE CONFIGURATION
title: streetAV
author: Tim Overstreet
description: > # Meta description of Homepage
  We provide high quality audio, video, lighting, and production solutions for churches. We offer expert guidance and support for new builds, remodels, events, and more. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://timothyoverstreet.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Tim Overstreet
  links:
    - https://www.instagram.com/timoverstreet/
    - https://www.facebook.com/timothy.overstreet.56
    - https://www.linkedin.com/in/tim-overstreet-883647186/

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  High quality audio, video, and production solutions for\n
  Churches  |  Schools  | Commercial Venues

hero_img: posts/Homepage v2.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/Homepage v2.jpg

email: timothydoverstreet@gmail.com # email for form submission

facebook_username: Tim-Overstreet-121748102557155 # replace with your_twitter_username or comment to remove link from footer
instagram_username: timoverstreet # replace with your_github_username or comment to remove link from footer
linkedin_username: tim-overstreet-883647186 # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
